// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/Francesco99975/reviews/internal/models"
	"github.com/Francesco99975/reviews/views/icons"
)

func Header(site models.Site) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"sticky top-0 z-50 bg-primary/95 backdrop-blur-md text-std shadow-lg border-b border-accent/20\" hx-boost=\"true\"><div class=\"container mx-auto px-4 lg:px-6\"><div class=\"flex items-center justify-between h-16\" x-data=\"{\n\t\t\t\t\t\t\tmobileMenuOpen: false,\n\t\t\t\t\t\t\tdarkMode: localStorage.getItem(&#39;darkMode&#39;) === &#39;true&#39; ? true :\n\t\t\t\t\t\t\t\t\t(localStorage.getItem(&#39;darkMode&#39;) === &#39;false&#39; ? false :\n\t\t\t\t\t\t\t\t\twindow.matchMedia(&#39;(prefers-color-scheme: dark)&#39;).matches)\n  \t\t\t\t\t\t}\" x-init=\"\n\t\t\t\t\tif(darkMode) {\n\t\t\t\t\t\tdocument.documentElement.classList.add(&#39;dark&#39;);\n\t\t\t\t\t} else {\n\t\t\t\t\t\tdocument.documentElement.classList.remove(&#39;dark&#39;);\n\t\t\t\t\t}\n\n\t\t\t\t\t$watch(&#39;darkMode&#39;, val =&gt; {\n\t\t\t\t\t\tlocalStorage.setItem(&#39;darkMode&#39;, val);\n\t\t\t\t\t\tif(val) {\n\t\t\t\t\t\t\tdocument.documentElement.classList.add(&#39;dark&#39;);\n\t\t\t\t\t\t} else {\n\t\t\t\t\t\t\tdocument.documentElement.classList.remove(&#39;dark&#39;);\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\n\n\t\t\t\t\twindow.matchMedia(&#39;(prefers-color-scheme: dark)&#39;).addEventListener(&#39;change&#39;, e =&gt; {\n\t\t\t\t\t\tif (localStorage.getItem(&#39;darkMode&#39;) === null) {\n\t\t\t\t\t\t\tdarkMode = e.matches;\n\t\t\t\t\t\t}\n\t\t\t\t\t\t});\n\t\t\t\t\t\"><div class=\"flex items-center gap-3 group\"><div class=\"transition-transform duration-300 group-hover:scale-110 group-hover:rotate-6 bg-std p-2 rounded-full\"><img src=\"/assets/dist/icon-optimized.svg\" alt=\"Go App Logo\" class=\"w-8 h-8\"></div><h1 class=\"text-xl lg:text-2xl font-bold text-std tracking-tight\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(site.AppName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/header.templ`, Line: 48, Col: 85}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h1></div><div class=\"hidden md:flex items-center gap-8\"><nav class=\"flex items-center gap-1\"><a href=\"/\" class=\"relative px-4 py-2 text-std font-medium rounded-lg transition-all duration-200 hover:bg-accent/20 hover:scale-105 focus:outline-none focus:ring-2 focus:ring-accent/50 group\"><span class=\"relative z-10\">Home</span> <span class=\"absolute inset-x-0 bottom-0 h-0.5 bg-accent scale-x-0 group-hover:scale-x-100 transition-transform duration-200 origin-left\"></span></a> <a href=\"/examples\" class=\"relative px-4 py-2 text-std font-medium rounded-lg transition-all duration-200 hover:bg-accent/20 hover:scale-105 focus:outline-none focus:ring-2 focus:ring-accent/50 group\"><span class=\"relative z-10\">Examples</span> <span class=\"absolute inset-x-0 bottom-0 h-0.5 bg-accent scale-x-0 group-hover:scale-x-100 transition-transform duration-200 origin-left\"></span></a> <a href=\"/about\" class=\"relative px-4 py-2 text-std font-medium rounded-lg transition-all duration-200 hover:bg-accent/20 hover:scale-105 focus:outline-none focus:ring-2 focus:ring-accent/50 group\"><span class=\"relative z-10\">About</span> <span class=\"absolute inset-x-0 bottom-0 h-0.5 bg-accent scale-x-0 group-hover:scale-x-100 transition-transform duration-200 origin-left\"></span></a></nav><button @click=\"darkMode = !darkMode\" class=\"p-2.5 rounded-full bg-accent/10 hover:bg-accent/20 transition-all duration-200 hover:scale-110 focus:outline-none focus:ring-2 focus:ring-accent/50 focus:ring-offset-2 focus:ring-offset-primary\" aria-label=\"Toggle dark mode\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Sun("stroke-std w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Moon("stroke-std w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</button></div><div class=\"flex items-center gap-2 md:hidden\"><button @click=\"darkMode = !darkMode\" class=\"p-2.5 rounded-full bg-accent/10 hover:bg-accent/20 transition-all duration-200 hover:scale-110 focus:outline-none focus:ring-2 focus:ring-accent/50\" aria-label=\"Toggle dark mode\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Sun("stroke-std w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Moon("stroke-std w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</button> <button @click=\"mobileMenuOpen = !mobileMenuOpen\" class=\"p-2.5 rounded-lg bg-accent/10 hover:bg-accent/20 transition-all duration-200 hover:scale-110 focus:outline-none focus:ring-2 focus:ring-accent/50\" aria-label=\"Toggle menu\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Hamburger("stroke-std w-6 h-6").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Close("stroke-std w-6 h-6").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</button></div><div x-show=\"mobileMenuOpen\" x-transition:enter=\"transition ease-out duration-200\" x-transition:enter-start=\"opacity-0 -translate-y-4\" x-transition:enter-end=\"opacity-100 translate-y-0\" x-transition:leave=\"transition ease-in duration-150\" x-transition:leave-start=\"opacity-100 translate-y-0\" x-transition:leave-end=\"opacity-0 -translate-y-4\" class=\"fixed inset-x-0 top-[64px] bg-primary/95 backdrop-blur-md shadow-2xl z-40 border-b border-accent/20\" x-cloak><nav class=\"container mx-auto px-4 py-6\"><div class=\"flex flex-col gap-2\"><a href=\"/\" class=\"px-4 py-3 text-std font-medium rounded-lg hover:bg-accent/20 transition-all duration-200 hover:translate-x-2 focus:outline-none focus:ring-2 focus:ring-accent/50\">Home</a> <a href=\"/examples\" class=\"px-4 py-3 text-std font-medium rounded-lg hover:bg-accent/20 transition-all duration-200 hover:translate-x-2 focus:outline-none focus:ring-2 focus:ring-accent/50\">Examples</a> <a href=\"/about\" class=\"px-4 py-3 text-std font-medium rounded-lg hover:bg-accent/20 transition-all duration-200 hover:translate-x-2 focus:outline-none focus:ring-2 focus:ring-accent/50\">About</a></div></nav></div></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func InformationalHeader(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<header class=\"sticky top-0 z-50 bg-std/80 backdrop-blur-md border-b border-primary/10 shadow-sm\"><div class=\"container mx-auto px-4 lg:px-6\"><div class=\"flex items-center justify-between h-16\" x-data=\"{\n\t\t\t\t\tdarkMode: localStorage.getItem(&#39;darkMode&#39;) === &#39;true&#39; ? true :\n\t\t\t\t\t\t\t(localStorage.getItem(&#39;darkMode&#39;) === &#39;false&#39; ? false :\n\t\t\t\t\t\t\twindow.matchMedia(&#39;(prefers-color-scheme: dark)&#39;).matches)\n\t\t\t\t}\" x-init=\"\n\t\t\t\t\tif(darkMode) {\n\t\t\t\t\t\tdocument.documentElement.classList.add(&#39;dark&#39;);\n\t\t\t\t\t} else {\n\t\t\t\t\t\tdocument.documentElement.classList.remove(&#39;dark&#39;);\n\t\t\t\t\t}\n\n\t\t\t\t\t$watch(&#39;darkMode&#39;, val =&gt; {\n\t\t\t\t\t\tlocalStorage.setItem(&#39;darkMode&#39;, val);\n\t\t\t\t\t\tif(val) {\n\t\t\t\t\t\t\tdocument.documentElement.classList.add(&#39;dark&#39;);\n\t\t\t\t\t\t} else {\n\t\t\t\t\t\t\tdocument.documentElement.classList.remove(&#39;dark&#39;);\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\n\t\t\t\t\twindow.matchMedia(&#39;(prefers-color-scheme: dark)&#39;).addEventListener(&#39;change&#39;, e =&gt; {\n\t\t\t\t\t\tif (localStorage.getItem(&#39;darkMode&#39;) === null) {\n\t\t\t\t\t\t\tdarkMode = e.matches;\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\t\t\t\t\"><!-- Logo and Title --><div class=\"flex items-center gap-3 group\"><div class=\"transition-transform duration-300 group-hover:scale-110 group-hover:rotate-6 bg-std p-2 rounded-full\"><img src=\"/assets/dist/icon-optimized.svg\" alt=\"Go App Logo\" class=\"w-8 h-8\"></div><h1 class=\"text-xl lg:text-2xl font-bold text-primary tracking-tight\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/header.templ`, Line: 155, Col: 82}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</h1></div><!-- Dark Mode Toggle --><button @click=\"darkMode = !darkMode\" class=\"p-2.5 rounded-full bg-primary/5 hover:bg-primary/10 transition-all duration-200 hover:scale-110 focus:outline-none focus:ring-2 focus:ring-primary/30 focus:ring-offset-2 focus:ring-offset-std\" aria-label=\"Toggle dark mode\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Sun("w-5 h-5 stroke-primary").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Moon("w-5 h-5 stroke-primary").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</button></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
