// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Francesco99975/reviews/views/icons"

func InvoiceForm(csrf string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-show=\"showForm\" x-transition:enter=\"transition ease-out duration-200\" x-transition:enter-start=\"opacity-0 transform scale-95\" x-transition:enter-end=\"opacity-100 transform scale-100\" x-transition:leave=\"transition ease-in duration-150\" x-transition:leave-start=\"opacity-100 transform scale-100\" x-transition:leave-end=\"opacity-0 transform scale-95\" class=\"mb-6 bg-std border-2 border-primary/20 rounded-lg p-4 md:p-6\" x-cloak><h2 class=\"text-lg font-semibold text-primary mb-4\">Create New Invoice</h2><form hx-post=\"/invoices\" hx-target=\"#invoice-list\" hx-swap=\"afterbegin\" hx-on::after-request=\"if(event.detail.successful) { showForm = false; this.reset(); }\" hx-indicator=\"#button-indicator\" hx-disabled-elt=\"find input[type=&#39;text&#39;], find button\" class=\"space-y-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CSRF(csrf).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!-- Total Amount Input --><div class=\"flex flex-col w-full\"><label for=\"total\" class=\"w-fit px-3 py-1 backdrop-blur-xl rounded bg-primary/10 text-primary text-sm font-medium mb-2\">Invoice Total</label><div class=\"relative\"><span class=\"absolute left-4 top-1/2 -translate-y-1/2 text-primary font-semibold text-lg\">$</span> <input class=\"w-full pl-10 pr-4 py-3 border-b-2 border-solid bg-transparent outline-none border-primary text-primary text-lg font-medium placeholder:text-primary/40 focus:border-accent transition-colors\" id=\"total\" name=\"total\" type=\"number\" step=\"0.01\" min=\"0\" placeholder=\"0.00\" required autofocus></div><p class=\"text-xs text-primary/50 mt-1 ml-1\">Enter the invoice amount in dollars</p></div><!-- Submit Button --><div class=\"flex gap-3 pt-2\"><button type=\"submit\" class=\"flex-1 sm:flex-none px-6 py-3 bg-success text-std rounded-lg font-medium hover:opacity-90 transition-opacity flex items-center justify-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Plus("w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span>Create Invoice</span></button><div id=\"button-indicator\" class=\"htmx-indicator absolute inset-0  flex items-center justify-center bg-accent/95 rounded-lg pointer-events-none\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Loading("w-6 h-6 animate-spin text-white").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><button type=\"button\" @click=\"showForm = false\" class=\"px-6 py-3 bg-std border-2 border-primary/20 text-primary rounded-lg font-medium hover:bg-primary/5 transition-colors\">Cancel</button></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
