// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Francesco99975/reviews/views/icons"

func ReviewForm(csrf string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"mb-8\" x-data=\"{ showForm: false }\"><!-- Toggle Button --><button @click=\"showForm = !showForm\" class=\"w-full md:w-auto flex items-center justify-center gap-2 px-6 py-3 bg-primary text-std rounded-xl font-semibold shadow-lg hover:opacity-90 transition-all mb-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Plus("w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span x-text=\"showForm ? &#39;Hide Form&#39; : &#39;Write Review&#39;\"></span></button><!-- Form --><div x-show=\"showForm\" x-transition:enter=\"transition ease-out duration-300\" x-transition:enter-start=\"opacity-0 transform scale-95\" x-transition:enter-end=\"opacity-100 transform scale-100\" x-transition:leave=\"transition ease-in duration-200\" x-transition:leave-start=\"opacity-100 transform scale-100\" x-transition:leave-end=\"opacity-0 transform scale-95\" class=\"bg-std border-2 border-primary rounded-2xl p-6 shadow-xl backdrop-blur-xl\" x-cloak><h3 class=\"text-xl font-bold text-primary mb-6\">Write a Review</h3><form hx-post=\"/reviews\" hx-target=\"#reviews-list\" hx-swap=\"afterbegin\" hx-on::after-request=\"if(event.detail.successful) { $el.reset(); showForm = false; }\" hx-indicator=\"#button-indicator\" hx-disabled-elt=\"find input[type=&#39;text&#39;], find button\" class=\"space-y-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CSRF(csrf).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- Invoice ID Input --><div><label for=\"invoice\" class=\"block text-sm font-semibold text-primary mb-2\">Invoice ID <span class=\"text-success\">*</span></label> <input type=\"text\" id=\"invoice\" name=\"invoice\" required placeholder=\"e.g., 550e8400-e29b-41d4-a716-446655440000\" pattern=\"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\" class=\"w-full px-4 py-3 bg-std border-2 border-primary rounded-xl font-mono text-sm focus:outline-none focus:ring-2 focus:ring-accent transition-all placeholder:text-primary placeholder:opacity-40\"><p class=\"text-xs text-primary opacity-60 mt-2\">Enter the UUID of the invoice you're reviewing</p></div><!-- Review Content Textarea --><div><label for=\"content\" class=\"block text-sm font-semibold text-primary mb-2\">Review Content <span class=\"text-success\">*</span></label> <textarea id=\"content\" name=\"content\" required minlength=\"10\" placeholder=\"Share your thoughts about this invoice...\" class=\"w-full px-4 py-3 bg-std border-2 border-primary rounded-xl focus:outline-none focus:ring-2 focus:ring-accent transition-all placeholder:text-primary placeholder:opacity-40 leading-relaxed\" rows=\"6\" x-data=\"{ count: 0 }\" @input=\"count = $el.value.length\"></textarea><div class=\"flex justify-between items-center mt-2\"><p class=\"text-xs text-primary opacity-60\">Minimum 10 characters</p><p class=\"text-xs text-primary opacity-60\" x-data=\"{ count: 0 }\" @input.document=\"count = document.getElementById(&#39;content&#39;).value.length\"><span x-text=\"count\"></span> characters</p></div></div><!-- Submit Button --><div class=\"flex gap-3\"><button type=\"submit\" class=\"flex-1 flex items-center justify-center gap-2 px-6 py-3 bg-accent text-std rounded-xl font-semibold shadow-lg hover:opacity-90 transition-all\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Send("w-5 h-5").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "Submit Review</button><div id=\"button-indicator\" class=\"htmx-indicator absolute inset-0  flex items-center justify-center bg-accent/95 rounded-lg pointer-events-none\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Loading("w-6 h-6 animate-spin text-white").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><button type=\"button\" @click=\"showForm = false\" class=\"px-6 py-3 border-2 border-primary text-primary rounded-xl font-semibold hover:bg-primary hover:text-std transition-all\">Cancel</button></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
