// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type TabConfig struct {
	ID       string
	Label    string
	Icon     templ.Component
	HasBadge bool
	Route    string
}

func TabNav(tabs []TabConfig, activeTab string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Mobile Bottom Tab Navigation --><nav class=\"fixed bottom-0 left-0 right-0 z-50 md:hidden bg-std border-t border-primary/10 backdrop-blur-xl safe-bottom\"><div class=\"flex h-16\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, tab := range tabs {
			templ_7745c5c3_Err = TabItem(TabItemProps{
				ID:        tab.ID,
				Label:     tab.Label,
				Icon:      tab.Icon,
				IsActive:  tab.ID == activeTab,
				HasBadge:  tab.HasBadge,
				HxGet:     tab.Route,
				HxTarget:  "#main-content",
				HxPushURL: tab.Route,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"absolute bottom-0 left-0 h-1 bg-linear-to-r from-primary to-accent transition-transform duration-300 ease-in-out\" :style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("'transform: translateX(' + (activeTab === '" + tabs[0].ID + "' ? '0%' : '100%') + '); width: 50%'")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/tab-nav.templ`, Line: 30, Col: 111}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"></div></nav><!-- Desktop Horizontal Tab Navigation --><nav class=\"hidden md:block fixed bottom-0 left-0 right-0 z-50 bg-std border-t border-primary/10 backdrop-blur-xl\"><div class=\"max-w-7xl mx-auto px-4\"><div class=\"flex items-center gap-2 h-16\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, tab := range tabs {
			templ_7745c5c3_Err = TabItemDesktop(TabItemProps{
				ID:        tab.ID,
				Label:     tab.Label,
				Icon:      tab.Icon,
				IsActive:  tab.ID == activeTab,
				HasBadge:  tab.HasBadge,
				HxGet:     tab.Route,
				HxTarget:  "#main-content",
				HxPushURL: tab.Route,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
