// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoices = `-- name: CountInvoices :one
SELECT COUNT(*) FROM invoices
`

func (q *Queries) CountInvoices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (id, total)
VALUES ($1, $2)
RETURNING id, total, created
`

type CreateInvoiceParams struct {
	ID    uuid.UUID `json:"id"`
	Total int32     `json:"total"`
}

type CreateInvoiceRow struct {
	ID      uuid.UUID  `json:"id"`
	Total   int32      `json:"total"`
	Created *time.Time `json:"created"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (*CreateInvoiceRow, error) {
	row := q.db.QueryRow(ctx, createInvoice, arg.ID, arg.Total)
	var i CreateInvoiceRow
	err := row.Scan(&i.ID, &i.Total, &i.Created)
	return &i, err
}

const deleteInvoice = `-- name: DeleteInvoice :execrows
DELETE FROM invoices
WHERE id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvoice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllInvoices = `-- name: GetAllInvoices :many
SELECT id, total, created
FROM invoices
ORDER BY created DESC
`

type GetAllInvoicesRow struct {
	ID      uuid.UUID  `json:"id"`
	Total   int32      `json:"total"`
	Created *time.Time `json:"created"`
}

func (q *Queries) GetAllInvoices(ctx context.Context) ([]*GetAllInvoicesRow, error) {
	rows, err := q.db.Query(ctx, getAllInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllInvoicesRow
	for rows.Next() {
		var i GetAllInvoicesRow
		if err := rows.Scan(&i.ID, &i.Total, &i.Created); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllInvoicesWithReview = `-- name: GetAllInvoicesWithReview :many
SELECT
  i.id AS invoice_id,
  i.total AS invoice_total,
  i.created AS invoice_created,
  r.content,
  r.created AS review_created
FROM invoices i
LEFT JOIN reviews r ON r.id = i.id
ORDER BY i.created DESC
`

type GetAllInvoicesWithReviewRow struct {
	InvoiceID      uuid.UUID        `json:"invoice_id"`
	InvoiceTotal   int32            `json:"invoice_total"`
	InvoiceCreated *time.Time       `json:"invoice_created"`
	Content        *string          `json:"content"`
	ReviewCreated  pgtype.Timestamp `json:"review_created"`
}

// struct: InvoiceWithReview
func (q *Queries) GetAllInvoicesWithReview(ctx context.Context) ([]*GetAllInvoicesWithReviewRow, error) {
	rows, err := q.db.Query(ctx, getAllInvoicesWithReview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllInvoicesWithReviewRow
	for rows.Next() {
		var i GetAllInvoicesWithReviewRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.InvoiceTotal,
			&i.InvoiceCreated,
			&i.Content,
			&i.ReviewCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, total, created
FROM invoices
WHERE id = $1
`

type GetInvoiceByIDRow struct {
	ID      uuid.UUID  `json:"id"`
	Total   int32      `json:"total"`
	Created *time.Time `json:"created"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, id uuid.UUID) (*GetInvoiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i GetInvoiceByIDRow
	err := row.Scan(&i.ID, &i.Total, &i.Created)
	return &i, err
}

const getInvoiceByIDWithReview = `-- name: GetInvoiceByIDWithReview :one
SELECT
  i.id AS invoice_id,
  i.total AS invoice_total,
  i.created AS invoice_created,
  r.content,
  r.created AS review_created
FROM invoices i
LEFT JOIN reviews r ON r.id = i.id
WHERE i.id = $1
`

type GetInvoiceByIDWithReviewRow struct {
	InvoiceID      uuid.UUID        `json:"invoice_id"`
	InvoiceTotal   int32            `json:"invoice_total"`
	InvoiceCreated *time.Time       `json:"invoice_created"`
	Content        *string          `json:"content"`
	ReviewCreated  pgtype.Timestamp `json:"review_created"`
}

// struct: InvoiceWithReview
func (q *Queries) GetInvoiceByIDWithReview(ctx context.Context, id uuid.UUID) (*GetInvoiceByIDWithReviewRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByIDWithReview, id)
	var i GetInvoiceByIDWithReviewRow
	err := row.Scan(
		&i.InvoiceID,
		&i.InvoiceTotal,
		&i.InvoiceCreated,
		&i.Content,
		&i.ReviewCreated,
	)
	return &i, err
}
