// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Invoice struct {
	ID      uuid.UUID  `json:"id"`
	Total   int32      `json:"total"`
	Created *time.Time `json:"created"`
	Updated *time.Time `json:"updated"`
}

type Review struct {
	ID      uuid.UUID  `json:"id"`
	Content string     `json:"content"`
	Created *time.Time `json:"created"`
	Updated *time.Time `json:"updated"`
}
