// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountInvoices(ctx context.Context) (int64, error)
	CountReviews(ctx context.Context) (int64, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (*CreateInvoiceRow, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (*CreateReviewRow, error)
	DeleteInvoice(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteReview(ctx context.Context, id uuid.UUID) (int64, error)
	GetAllInvoices(ctx context.Context) ([]*GetAllInvoicesRow, error)
	// struct: InvoiceWithReview
	GetAllInvoicesWithReview(ctx context.Context) ([]*GetAllInvoicesWithReviewRow, error)
	GetAllReviews(ctx context.Context) ([]*GetAllReviewsRow, error)
	GetInvoiceByID(ctx context.Context, id uuid.UUID) (*GetInvoiceByIDRow, error)
	// struct: InvoiceWithReview
	GetInvoiceByIDWithReview(ctx context.Context, id uuid.UUID) (*GetInvoiceByIDWithReviewRow, error)
	GetReviewByID(ctx context.Context, id uuid.UUID) (*GetReviewByIDRow, error)
}

var _ Querier = (*Queries)(nil)
