// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countReviews = `-- name: CountReviews :one
SELECT COUNT(*) FROM reviews
`

func (q *Queries) CountReviews(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countReviews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (id, content)
VALUES ($1, $2)
RETURNING id, content, created
`

type CreateReviewParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

type CreateReviewRow struct {
	ID      uuid.UUID  `json:"id"`
	Content string     `json:"content"`
	Created *time.Time `json:"created"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (*CreateReviewRow, error) {
	row := q.db.QueryRow(ctx, createReview, arg.ID, arg.Content)
	var i CreateReviewRow
	err := row.Scan(&i.ID, &i.Content, &i.Created)
	return &i, err
}

const deleteReview = `-- name: DeleteReview :execrows
DELETE FROM reviews
WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReview, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllReviews = `-- name: GetAllReviews :many
SELECT id, content, created
FROM reviews
ORDER BY created DESC
`

type GetAllReviewsRow struct {
	ID      uuid.UUID  `json:"id"`
	Content string     `json:"content"`
	Created *time.Time `json:"created"`
}

func (q *Queries) GetAllReviews(ctx context.Context) ([]*GetAllReviewsRow, error) {
	rows, err := q.db.Query(ctx, getAllReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllReviewsRow
	for rows.Next() {
		var i GetAllReviewsRow
		if err := rows.Scan(&i.ID, &i.Content, &i.Created); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, content, created
FROM reviews
WHERE id = $1
`

type GetReviewByIDRow struct {
	ID      uuid.UUID  `json:"id"`
	Content string     `json:"content"`
	Created *time.Time `json:"created"`
}

func (q *Queries) GetReviewByID(ctx context.Context, id uuid.UUID) (*GetReviewByIDRow, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i GetReviewByIDRow
	err := row.Scan(&i.ID, &i.Content, &i.Created)
	return &i, err
}
